version: 1

before:
  hooks:
    - go mod tidy

builds:
  - binary: retro_aim_server
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/server
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=oa64-clang{{- end }}
        {{- end }}
        {{- if eq .Os "linux" }}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Os "windows" }}CC=x86_64-w64-mingw32-gcc{{- end }}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    files:
      - LICENSE
      - src: config/settings.{{- if eq .Os "windows" }}bat{{ else }}env{{ end }}
        strip_parent: true
      - src: scripts/run.{{- if eq .Os "windows" }}cmd{{ else }}sh{{ end }}
        strip_parent: true
    name_template: >-
      {{ .Binary }}.{{ .Version }}.
      {{- if eq .Os "darwin"}}macos
      {{- else }}{{ .Os }}{{ end }}.
      {{- if eq .Os "darwin"}}{{- if eq .Arch "amd64" }}intel_x86_64{{ else }}apple_silicon{{ end }}
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}