with-expecter: True
dir: "{{.InterfaceDir}}"
mockname: "mock{{.InterfaceName}}"
inpackage: True
packages:
  github.com/mk6i/retro-aim-server/server/oscar:
    interfaces:
      AuthService:
        config:
          filename: "mock_auth_test.go"
      Handler:
        config:
          filename: "mock_handler_test.go"
      UserManager:
        config:
          filename: "mock_user_manager_test.go"
      OnlineNotifier:
        config:
          filename: "mock_online_notifier_test.go"
  github.com/mk6i/retro-aim-server/server/http:
    interfaces:
      UserManager:
        config:
          filename: "mock_user_manager_test.go"
      SessionRetriever:
        config:
          filename: "mock_session_retriever_test.go"
      ChatRoomRetriever:
        config:
          filename: "mock_chat_room_retriever_test.go"
      ChatRoomCreator:
        config:
          filename: "mock_chat_room_creator_test.go"
      ChatSessionRetriever:
        config:
          filename: "mock_chat_session_retriever_test.go"
  github.com/mk6i/retro-aim-server/server/oscar/handler:
    interfaces:
      ResponseWriter:
        config:
          filename: "mock_response_writer_test.go"
      ChatService:
        config:
          filename: "mock_chat_test.go"
      ChatNavService:
        config:
          filename: "mock_chat_nav_test.go"
      FeedbagService:
        config:
          filename: "mock_feedbag_test.go"
      ICBMService:
        config:
          filename: "mock_icbm_test.go"
      OServiceService:
        config:
          filename: "mock_oservice_test.go"
      LocateService:
        config:
          filename: "mock_locate_test.go"
      BuddyService:
        config:
          filename: "mock_buddy_test.go"
      BARTService:
        config:
          filename: "mock_bart_test.go"
      PermitDenyService:
        config:
          filename: "mock_permit_deny_test.go"
  github.com/mk6i/retro-aim-server/foodgroup:
    interfaces:
      FeedbagManager:
        config:
          filename: "mock_feedbag_manager_test.go"
      UserManager:
        config:
          filename: "mock_user_manager_manager_test.go"
      ProfileManager:
        config:
          filename: "mock_profile_manager_test.go"
      ChatSessionRegistry:
        config:
          filename: "mock_chat_session_registry_test.go"
      SessionManager:
        config:
          filename: "mock_session_manager_test.go"
      MessageRelayer:
        config:
          filename: "mock_message_relayer_test.go"
      ChatMessageRelayer:
        config:
          filename: "mock_chat_message_relayer_test.go"
      ChatRoomRegistry:
        config:
          filename: "mock_chat_room_registry_test.go"
      BARTManager:
        config:
          filename: "mock_bart_manager_test.go"
      LegacyBuddyListManager:
        config:
          filename: "mock_legacy_buddy_list_manager_test.go"
      CookieBaker:
        config:
          filename: "mock_cookie_baker_test.go"
      buddyBroadcaster:
        config:
          filename: "mock_buddy_broadcaster_test.go"