with-expecter: True
dir: "{{.InterfaceDir}}"
mockname: "mock{{.InterfaceName}}"
inpackage: True
packages:
  github.com/mkaminski/goaim/server:
    interfaces:
      BuddyHandler:
        config:
          filename: "buddy_mock_test.go"
      ChatHandler:
        config:
          filename: "chat_mock_test.go"
      ChatNavHandler:
        config:
          filename: "chat_nav_mock_test.go"
      FeedbagHandler:
        config:
          filename: "feedbag_mock_test.go"
      ICBMHandler:
        config:
          filename: "icbm_mock_test.go"
      LocateHandler:
        config:
          filename: "locate_mock_test.go"
      OServiceHandler:
        config:
          filename: "oservice_mock_test.go"
      OServiceBOSHandler:
        config:
          filename: "oservice_bos_mock_test.go"
      OServiceChatHandler:
        config:
          filename: "oservice_chat_mock_test.go"
  github.com/mkaminski/goaim/handler:
    interfaces:
      FeedbagManager:
        config:
          filename: "feedbag_manager_mock_test.go"
      UserManager:
        config:
          filename: "user_manager_manager_mock_test.go"
      ProfileManager:
        config:
          filename: "profile_manager_mock_test.go"
      SessionManager:
        config:
          filename: "session_manager_mock_test.go"
      MessageRelayer:
        config:
          filename: "message_relayer_mock_test.go"
      ChatMessageRelayer:
        config:
          filename: "chat_message_relayer_mock_test.go"